version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust

  - package-ecosystem: npm
    directory: /desktop/web
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - web

  - package-ecosystem: nuget
    directory: /desktop
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: nuget
    directory: /cloud
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dotnet
